// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEwQ3UxEbK_DmIMHMHH9N5T24wmeRuaiI',
    appId: '1:133280892873:web:373752dbd83d6c5a474a18',
    messagingSenderId: '133280892873',
    projectId: 'book-summary-app-57155',
    authDomain: 'book-summary-app-57155.firebaseapp.com',
    storageBucket: 'book-summary-app-57155.appspot.com',
    measurementId: 'G-JLP0SV7NJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkIoXV93oYv-lWEN2v_W4gzn9tQEERYc',
    appId: '1:133280892873:android:e932bbdcdeceb8cb474a18',
    messagingSenderId: '133280892873',
    projectId: 'book-summary-app-57155',
    storageBucket: 'book-summary-app-57155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYqLNG_oZn9FchQMUdxGgx73vlwJm4h8',
    appId: '1:133280892873:ios:d6e73c9d22a11be2474a18',
    messagingSenderId: '133280892873',
    projectId: 'book-summary-app-57155',
    storageBucket: 'book-summary-app-57155.appspot.com',
    iosBundleId: 'com.example.bookSummary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYqLNG_oZn9FchQMUdxGgx73vlwJm4h8',
    appId: '1:133280892873:ios:d6e73c9d22a11be2474a18',
    messagingSenderId: '133280892873',
    projectId: 'book-summary-app-57155',
    storageBucket: 'book-summary-app-57155.appspot.com',
    iosBundleId: 'com.example.bookSummary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEwQ3UxEbK_DmIMHMHH9N5T24wmeRuaiI',
    appId: '1:133280892873:web:40b299eb86601259474a18',
    messagingSenderId: '133280892873',
    projectId: 'book-summary-app-57155',
    authDomain: 'book-summary-app-57155.firebaseapp.com',
    storageBucket: 'book-summary-app-57155.appspot.com',
    measurementId: 'G-S1PELTFJJH',
  );
}
